// Regenerates src/lib/db-ddl.ts from scripts/db-ddl-raw.sql.
//
// Pipeline (see src/lib/db-ddl.ts header):
//   1. bunx prisma migrate diff --from-empty --to-schema-datamodel \
//        prisma/schema.prisma --script > scripts/db-ddl-raw.sql
//   2. node scripts/gen-ddl.mjs
//
// Transformations applied to the raw diff output:
//   - CREATE TABLE "X"     -> CREATE TABLE IF NOT EXISTS "X"
//   - CREATE INDEX/UNIQUE INDEX -> ... IF NOT EXISTS ...
//   - PRAGMA / transaction noise dropped; statements split on ";"
//
// The SCHEMA_UPGRADES block below lists ALTER TABLE statements for columns
// added to ALREADY-EXISTING tables (CREATE TABLE IF NOT EXISTS cannot add
// columns to a table that exists). SQLite has no ADD COLUMN IF NOT EXISTS,
// so these rely on the bootstrap executor tolerating "duplicate column"
// errors — re-running is always safe.
import { readFileSync, writeFileSync } from "node:fs";

const RAW = "scripts/db-ddl-raw.sql";
const OUT = "src/lib/db-ddl.ts";

// Columns added to existing tables after their first CREATE TABLE shipped.
// Keep newest-first ordering per table; append new entries here on upgrade.
const SCHEMA_UPGRADES = [
  'ALTER TABLE "AuditLog" ADD COLUMN "organizationId" TEXT;',
  'ALTER TABLE "AuditLog" ADD COLUMN "authorizationRole" TEXT;',
  'ALTER TABLE "ResponseCase" ADD COLUMN "outcomeCategory" TEXT;',
  'ALTER TABLE "ResponseCase" ADD COLUMN "outcomeSummary" TEXT;',
];

const raw = readFileSync(RAW, "utf8");

// Split into statements on ";" at end-of-line; drop comments/blank/PRAGMA.
const statements = [];
for (const chunk of raw.split(/;\s*\n/)) {
  const cleaned = chunk
    .split("\n")
    .filter((line) => !/^\s*--/.test(line)) // remove "-- CreateTable" hints
    .join("\n")
    .trim();
  if (!cleaned) continue;
  if (/^PRAGMA/i.test(cleaned)) continue;
  if (/^(BEGIN|COMMIT)/i.test(cleaned)) continue;
  statements.push(cleaned);
}

const transformed = statements.map((stmt) => {
  if (/^CREATE TABLE /i.test(stmt)) {
    return stmt.replace(/^CREATE TABLE /i, "CREATE TABLE IF NOT EXISTS ");
  }
  if (/^CREATE UNIQUE INDEX /i.test(stmt)) {
    return stmt.replace(/^CREATE UNIQUE INDEX /i, "CREATE UNIQUE INDEX IF NOT EXISTS ");
  }
  if (/^CREATE INDEX /i.test(stmt)) {
    return stmt.replace(/^CREATE INDEX /i, "CREATE INDEX IF NOT EXISTS ");
  }
  return stmt;
});

const all = [...transformed, ...SCHEMA_UPGRADES];

const body = all.map((stmt) => `  ${JSON.stringify(stmt)}`).join(",\n");

const out = `// AUTO-GENERATED by scripts/gen-ddl.mjs from prisma/schema.prisma — do NOT edit by hand.
// Idempotent SQLite DDL (CREATE ... IF NOT EXISTS) executed once per server
// instance by src/lib/db-bootstrap.ts so deployments without a pre-provisioned
// database file (e.g. Vercel serverless /tmp) self-provision at cold start.
// The ALTER TABLE entries at the end upgrade ALREADY-EXISTING databases with
// columns added after their first creation (the bootstrap executor tolerates
// "duplicate column" errors, so re-running is always safe).
// Regenerate: bunx prisma migrate diff --from-empty --to-schema-datamodel \\
//   prisma/schema.prisma --script > scripts/db-ddl-raw.sql && node scripts/gen-ddl.mjs
export const SQLITE_DDL: string[] = [
${body},
];
`;

writeFileSync(OUT, out, "utf8");
console.log(`gen-ddl: wrote ${all.length} statements (${transformed.length} from diff + ${SCHEMA_UPGRADES.length} upgrades) -> ${OUT}`);
